[phases.setup]
nixPkgs = ["python311", "postgresql"]

[phases.install]
cmds = ["cd api && pip install -r requirements.txt"]

[start]
cmd = "cd api && uvicorn main:app --host 0.0.0.0 --port ${PORT:-8001}"
